module-template: ! 'module MODULE_NAME where

'
extensions:
  TemplateHaskell: true
  OverloadedStrings: true
  ImplicitPrelude: false
  QuasiQuotes: true
  TypeFamilies: true
  DeriveDataTypeable: true
  MultiParamTypeClasses: true
environment: ghc-7.4.2-unstable
cabal-file: project.cabal
version: 1
extra-packages: ''
ghc-args: []
excluded-modules: []
